### ISSUE TITLE
Does it make sense to mark function as `inline function`?

### ISSUE THREAD

**Issue by beryll1um** [nicro/etl#2]
https://github.com/nicro/etl/blob/3ec6ecdcdb61c7cbd4308ecffbd98792d5e3faf7/etl/inc/string.hpp#L14
# About the concept of an inline function in the C++ standard
You may know that compilers completely ignore this as a recommendation for function inlining, and rightly so. Compilers middle-end can analyze your function call statistics and it properties to determine the best strategy in specific case. Another case of usage of `inline` specifier is an `inline function` declaration. In standard and notes it's mentioned as a way to define specific TU functions in headers right away. But don't be too gullible! In fact, there are devilish condition defined by this specifier, without knowing about which you can run into very difficult to catch errors!

1. The `inline` specifier used relative to a function works much more like symbolic mark than the current function specifier.
if you mark any function with that name, it will mean that all functions with that name will be interpreted as instances of `inline function`, REGARDLESS of the TU!

2. `inline function` is defined differently in different translation units, the behavior is undefined!
It means that if you define same `inline function` in different TU and will try to call it from third-party TU you can wait an undefined behavior from it.

... and lots other specific things that related with the nature of external linkage objects.

# Back to the problem
It would be better to remove this specifier for the current function, because this is not really a `inline function` usage case, and this can cause some problems in specific cases. External linkage still carry a lot of responsibility, so it's not a good practice to push any garbage as it.

IT'S A LOT OF BETTER TO DO AN MISTAKE AND CATCH AN ERROR, THAN DON'T CATCH AN ERROR AND DROP PRODUCTION
© Any smart person

**Comment by nicro** [comment]
### Thank you very much for your contribution!

In this case, it is not possible to simply drop `inline` specifier, because string.hpp is included
from various files (tests as far as I remember) and you would run into multiple definition error.

### There are multiple approaches to this problem.
1. Declare the function `static` to force internal linkage
2. Add `inline` specifier


The first approach would cause some overhead, because this would 'copy' the function definition to every TU.
The second approach is in my opinion better, because the `inline` keyword purpose has developed over time to solve exactly that problem.

Your drawback of `inline` function comment:
1. Not sure if that is true. I tried to declare and define a function in other TU and that works fine. Could you provide some source/example of that scenario? 

2. This might be legit, but I can hardly imagine such a case, because one would need to write smth like this and access etl namespace implying he knows what he is doing.

```cpp
namespace etl {
    inline void memcpy(void *target, const void *src, size_t cnt) {
        // Other memcpy definition causing UB
    }
}
```
Additionally, this is a common practise in MSVC. Check out for example [std::stoi implementation](https://github.com/microsoft/STL/blob/main/stl/inc/string#L89
).

**Comment by beryll1um** [comment]
@nicro, I'm writing this in its entirety to refresh my memory, I was completely convinced this was a common mistake. Sorry for this.

Let's start from entirely common explanation: *Your not a compiler, so the count of standard defined static linkage objects is not your problem.* To be clear, a big part of C++ development tends to be understanding and trusting compiler optimization mechanisms. You should be aware that the compiler will optimize the number of objects, so you end up with only one function. So linkage it's nothing more than an abstraction for the developer. Don't dwell on it.

```cpp
/* a.cpp */

int next()
{
  return 2*2;
}

int tu_a_call()
{
  return next();
}
```
```cpp
/* main.cpp */

#include <iostream>

int tu_a_call();

inline int next()
{
  return 3*3;
}

int main()
{
  std::cout << tu_a_call() << std::endl;
  std::cout << next() << std::endl;
}
```
```bash
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.0 (GCC)
$ gcc a.cpp main.cpp
$ ./a.out
4
4
$ gcc -O2 a.cpp main.cpp
$ ./a.out
4
9
```
It's simplest undefined behavior you can receive with the mentioned "symbolic mark" behavior. So, the whole part of C++ community don't doing this. Much more better will be leave only declaration of this function in header, and move implementaion in scope of CPP file to don't share it across the TU's and make it safer (or make it static). More information in this article: https://en.cppreference.com/w/cpp/language/inline](https://en.cppreference.com/w/cpp/language/inline

**Comment by nicro** [comment]
Thank you for example, now I understand what you mean.

If we think about it more globally, it is not only `inline function` problem.
`constexpr` functions, class methods and `template` functions are all implicitly declared `inline` according to [cppreference](https://en.cppreference.com/w/cpp/language/inline).
This means, the following example would produce an UB as well, although it is not explicitly marked inline.

```cpp
/* a.cpp */

template <class T>
int next()
{
    T t = 2 * 2;
    return int{t};
}

int tu_a_call()
{
  return next<int>();
}
```

```cpp
#include <iostream>

int tu_a_call();

template <class T>
int next()
{
    T t = 3 * 3;
    return int{t};
}

int main()
{
  std::cout << tu_a_call() << std::endl;
  std::cout << next<int>() << std::endl;
}
```

```bash
g++ a.cpp main.cpp && ./a.out
4
4

g++ -O2 a.cpp main.cpp && ./a.out
4
9
```

Same applies to methods and `constexpr` functions. So in fact much more functions are possibly affected by this problem.
Forcing all this stuff to be defined in seperate cpp file would make writing header-only generally almost impossible, which sounds absurd, doesn't it ?

Static makes sense for me neither, because there is no point of linking it internally and dublicating code in each TU. Also, if we approach this consistently, all the `templates` should've been marked `static` too.

Luckily, isolating it to namespace solves the issue as long the second function definition is not in it too.
I do admit this issue exists, but its very hard to avoid completely. Thus I think this risk can be tolerated as long as it is in the own namespace.

**Comment by beryll1um** [comment]
Your right, but In your case, you can localize your non-template function in TU and provide a declaration in header for every TU. It will prevent any above described errors. Usually, it's a good practice, any case why do we don't declare any function as `inline function` if we store it in namespace? By the way, a lot of people like to use `using namespace` feature, and if they don't know about your internal implementations, they might accidentally hit that name and get a hard-to-find bug.
